Alisha adnan

870931
# ***NUMPY TASKS***


In [ ]:
import numpy as np

#TASK 1
array = np.array([10, 20, 30, 40, 50])
print ("Sum:",np.sum(array))
print ("Average:",np.mean(array))
print ("Maximum:",np.max(array))
print ("Minimum:",np.min(array))

Sum: 150
Average: 30.0
Maximum: 50
Minimum: 10


In [ ]:
#TASK 2
array = np.array([ 45, 80, 30, 90, 55, 20])
print (array[array >= 50 ] )

[80 90 55]


In [ ]:
#TASK 3
numbers = np.array([1, 2, 3, 4, 5, 6])
print (numbers.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [ ]:
#TASK 4
marks = np.random.randint(40, 100, 10)
print ("Marks:",marks)


print ("Average:",np.mean(marks))
print ("Highest marks:",np.max(marks))
print ("Lowest marks:",np.min(marks))

Marks: [89 75 92 95 54 87 96 40 81 44]
Average: 75.3
Highest marks: 96
Lowest marks: 40


In [ ]:
#TASK 5

masks= np.array([35, 67, 89, 45, 90, 22, 70, 58])

passed = masks[masks >= 50 ]
failed = masks[masks < 50 ]

print ("Passed marks:")
print (passed)
print ("\nfailed marks:")
print (failed)

print ("\nNumber of passed students:", len(passed))
print ("Number of passed students:", len(failed))

Passed marks:
[67 89 90 70 58]

failed marks:
[35 45 22]

Number of passed students: 5
Number of passed students: 3
